# -*- coding: utf-8 -*-
"""imu_feature_extractoripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9jSU1AGdQnrfFVtg4JQlirFeFIYmCL1
"""

import numpy as np
import pandas as pd
from scipy.io import loadmat
from scipy.signal import welch
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# ── PATHS (Local) ────────────────────────────────────────
_HERE      = Path(__file__).resolve().parent.parent  # Phase_1/
DATA_DIR   = _HERE / "data" / "utd-mhad" / "Inertial"
OUTPUT_CSV = _HERE / "results" /  "imu_features"/"imu_features.csv"

ACTION_ID     = 22
NUM_SUBJECTS  = 8
NUM_TRIALS    = 4
SAMPLING_RATE = 50

# ── LOAD .mat FILE ────────────────────────────────────────
def load_mat_file(filepath):
    mat = loadmat(str(filepath))
    if 'd_iner' in mat:
        data = mat['d_iner']
    else:
        keys = [k for k in mat.keys() if not k.startswith('_')]
        data = mat[keys[0]]
    return data.astype(np.float64)

# ── SPLIT ACCEL / GYRO ────────────────────────────────────
def split_sensors(data):
    return data[:, 0:3], data[:, 3:6]

# ── FEATURE FUNCTIONS ─────────────────────────────────────
def accel_magnitude(accel):
    return np.sqrt(np.sum(accel ** 2, axis=1))

def gyro_magnitude(gyro):
    return np.sqrt(np.sum(gyro ** 2, axis=1))

def stride_rate(accel_mag, fs=SAMPLING_RATE):
    freqs, psd = welch(accel_mag, fs=fs, nperseg=min(256, len(accel_mag)))
    mask = (freqs >= 1.0) & (freqs <= 4.0)
    if not mask.any():
        return 0.0
    return float(freqs[mask][np.argmax(psd[mask])])

def smoothness(accel, fs=SAMPLING_RATE):
    mag = accel_magnitude(accel)
    freqs, psd = welch(mag, fs=fs, nperseg=min(256, len(mag)))
    psd_norm = psd / (psd.max() + 1e-10)
    freq_spacing = freqs[1] - freqs[0] if len(freqs) > 1 else 1.0
    return float(-np.sum(np.sqrt(freq_spacing ** 2 + np.diff(psd_norm) ** 2)))

# ── EXTRACT ALL FEATURES FOR ONE FILE ────────────────────
def extract_features(filepath):
    data = load_mat_file(filepath)
    accel, gyro = split_sensors(data)
    a_mag = accel_magnitude(accel)
    g_mag = gyro_magnitude(gyro)
    sr    = stride_rate(a_mag)
    return {
        "peak_accel_mag":      float(np.max(a_mag)),
        "mean_accel_mag":      float(np.mean(a_mag)),
        "std_accel_mag":       float(np.std(a_mag)),
        "mean_gyro_mag":       float(np.mean(g_mag)),
        "std_gyro_mag":        float(np.std(g_mag)),
        "stride_rate_hz":      sr,
        "steps_per_min":       round(sr * 60, 2),
        "movement_smoothness": smoothness(accel),
    }

# ── BATCH PROCESS ALL 32 SAMPLES ─────────────────────────
def process_all():
    records, missing = [], []

    for subject in range(1, NUM_SUBJECTS + 1):
        for trial in range(1, NUM_TRIALS + 1):
            fname = f"a{ACTION_ID}_s{subject}_t{trial}_inertial.mat"
            fpath = DATA_DIR / fname

            if not fpath.exists():
                print(f"  [MISSING] {fname}")
                missing.append(fname)
                continue
            try:
                feats = extract_features(fpath)
                feats["subject"] = subject
                feats["trial"]   = trial
                # Re-add the missing 'file' key
                feats["file"]    = fname
                records.append(feats)
                print(f"  [OK] {fname} | stride={feats['stride_rate_hz']:.2f} Hz | peak={feats['peak_accel_mag']:.3f}")
            except Exception as e:
                print(f"  [ERROR] {fname}: {e}")

    if not records:
        raise RuntimeError("No files processed. Check your DATA_DIR path and filenames.")

    df = pd.DataFrame(records)
    cols = ["subject", "trial", "file"] + [c for c in df.columns if c not in ["subject","trial","file"]]
    return df[cols]

# ── MAIN ──────────────────────────────────────────────────
print("=" * 50)
print("  IMU Feature Extractor — UTD-MHAD Jogging")
print("=" * 50)

df = process_all()

print("\n--- Summary ---")
print(df[["peak_accel_mag","mean_accel_mag","stride_rate_hz","steps_per_min"]].describe().round(3))

OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True);
df.to_csv(OUTPUT_CSV, index=False)
print(f"\n Saved → {OUTPUT_CSV}  ({len(df)} samples)")
