#!/usr/bin/env python3
"""
Phase 2 IMU Feature Extractor
-----------------------------
Extracts 11 sprint-specific IMU features from the perfectly synchronized
Watch Sensor Logger CSVs generated by sync_trim_imu.py. 

Features extracted match the 23-feature goal when combined with video data.
"""

import numpy as np
import pandas as pd
from scipy.signal import welch
from pathlib import Path

# ── CONFIG ────────────────────────────────────────────────────────────────────
_HERE = Path(__file__).resolve().parent
PROJECT_ROOT = _HERE.parent.parent

INPUT_DIR  = PROJECT_ROOT / "Phase_2" / "results" / "synced_imu"
OUTPUT_DIR = PROJECT_ROOT / "Phase_2" / "results" / "imu_features"
OUTPUT_CSV = OUTPUT_DIR / "imu_features.csv"

# ── MATH & FEATURES ───────────────────────────────────────────────────────────

def get_magnitude(x, y, z):
    """Euclidean norm of 3D array"""
    return np.sqrt(x**2 + y**2 + z**2)

def get_dominant_frequency(signal, fs):
    """Finds peak frequency using Welch's power spectral density"""
    if len(signal) < 10:
        return 0.0
    # nperseg must be <= length of signal
    nperseg = min(256, len(signal))
    freqs, psd = welch(signal, fs=fs, nperseg=nperseg)
    
    # Restrict to realistic sprint frequencies (1.0 Hz - 5.0 Hz)
    mask = (freqs >= 1.0) & (freqs <= 5.0)
    if not mask.any():
        # Fallback if no energy in that band
        return float(freqs[np.argmax(psd)])
        
    valid_freqs = freqs[mask]
    valid_psd = psd[mask]
    return float(valid_freqs[np.argmax(valid_psd)])

def get_sparc_smoothness(signal, fs):
    """
    Computes spectral arc length (SPARC) as a measure of smoothness.
    Higher (closer to 0) = smoother, Lower (more negative) = jerky.
    """
    if len(signal) < 10:
        return 0.0
        
    nperseg = min(256, len(signal))
    freqs, psd = welch(signal, fs=fs, nperseg=nperseg)
    
    # Normalize PSD
    psd_norm = psd / (psd.max() + 1e-10)
    freq_spacing = freqs[1] - freqs[0] if len(freqs) > 1 else 1.0
    
    # Arc length of the spectral curve
    arc_length = -np.sum(np.sqrt(freq_spacing**2 + np.diff(psd_norm)**2))
    return float(arc_length)

# ── MAIN PROCESSOR ────────────────────────────────────────────────────────────

def process_file(csv_path: Path) -> dict:
    """Read one synced IMU CSV and return its 11 aggregated features."""
    df = pd.read_csv(csv_path)
    
    if len(df) < 10:
        raise ValueError("Too few samples to process.")
        
    # Dynamically calculate exact sample rate since Galaxy Watch fluctuates
    duration = df['seconds_elapsed'].iloc[-1] - df['seconds_elapsed'].iloc[0]
    if duration <= 0:
        fs = 38.0  # fallback
    else:
        fs = (len(df) - 1) / duration

    # 1. Magnitudes
    accel_mag = get_magnitude(df['ax'], df['ay'], df['az'])
    gyro_mag  = get_magnitude(df['gx'], df['gy'], df['gz'])
    
    # 2. Frequencies (Stride Rate)
    a_freq = get_dominant_frequency(accel_mag, fs)
    g_freq = get_dominant_frequency(gyro_mag, fs)
    
    # Build dictionary of 11 features
    features = {
        'athlete': csv_path.stem.replace('_synced_imu', ''),
        
        # Accelerometer Features
        'peak_accel_mag': round(float(accel_mag.max()), 3),
        'mean_accel_mag': round(float(accel_mag.mean()), 3),
        'std_accel_mag':  round(float(accel_mag.std()), 3),    # Variability
        'stride_rate_accel_hz': round(a_freq, 2),
        'movement_smoothness_accel': round(get_sparc_smoothness(accel_mag, fs), 3),
        
        # Gyroscope Features
        'peak_gyro_mag':  round(float(gyro_mag.max()), 3),
        'mean_gyro_mag':  round(float(gyro_mag.mean()), 3),
        'std_gyro_mag':   round(float(gyro_mag.std()), 3),     # Variability
        'stride_rate_gyro_hz': round(g_freq, 2),
        'movement_smoothness_gyro': round(get_sparc_smoothness(gyro_mag, fs), 3),
        
        # Derived
        'steps_per_min_gyro': round(g_freq * 60, 1)
    }
    
    return features


def main():
    print(f"{'='*50}\n  Phase 2: Sprint IMU Feature Extractor\n{'='*50}")
    
    if not INPUT_DIR.exists():
        raise FileNotFoundError(f"Cannot find {INPUT_DIR}. Run sync_trim_imu.py first.")
        
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    files = sorted(list(INPUT_DIR.glob("*_synced_imu.csv")))
    print(f"Found {len(files)} synced IMU files to process.\n")
    
    results = []
    
    for i, file_path in enumerate(files, 1):
        print(f"[{i}/{len(files)}] Processing {file_path.name}... ", end="")
        try:
            feats = process_file(file_path)
            results.append(feats)
            print(f" {feats['peak_accel_mag']} m/s² peak | {feats['stride_rate_gyro_hz']} Hz")
        except Exception as e:
            print(f" Error: {e}")
            
    if results:
        df_out = pd.DataFrame(results)
        df_out.to_csv(OUTPUT_CSV, index=False)
        print(f"\n All done! Extracted 11 sprint features for {len(results)} athletes.")
        print(f" Saved to: {OUTPUT_CSV}")
        
        print("\nPreview of top metrics:")
        print(df_out[['athlete', 'peak_accel_mag', 'stride_rate_gyro_hz', 'movement_smoothness_accel']].head())
    else:
        print("\n Extracted 0 features.")


if __name__ == "__main__":
    main()
